name: Run tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # https://github.com/cclauss/GitHub-Action-for-pytest
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest --rootdir='/tests'
