name: Run tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # https://github.com/fylein/python-pytest-github-action
      - name: Python Pylin GitHub Action
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pytest test/unit
